### ISSUE TITLE
Paths with blanks

### ISSUE THREAD

**Issue by nowrap** [rain0r/ampd#11]
Hello,
i started using ampd today for our rpg jitsi group as a controller for an icecast stream via mpd.

I have folders with blanks in the name. This throws execeptions:
`
2020-06-05 11:57:51.095  INFO 20704 --- [0.0-8080-exec-1] org.hihn.ampd.server.util.AmpdUtils      : Error while search covers in: RPGMix/Clash of the titans

java.nio.file.NoSuchFileException: RPGMix/Clash of the titans
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432) ~[na:na]
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:539) ~[na:na]
        at org.hihn.ampd.server.util.AmpdUtils.scanDir(AmpdUtils.java:64) ~[ampd-1.1.3.jar:1.1.3]
        at org.hihn.ampd.server.service.CoverArtFetcherService.findAlbumCover(CoverArtFetcherService.java:131) ~[ampd-1.1.3.jar:1.1.3]
        at org.hihn.ampd.server.controller.CoverController.findCoverByPath(CoverController.java:74) ~[ampd-1.1.3.jar:1.1.3]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

`

I am not that familiar with java to fix this locally.

Regards
nowrap

**Comment by rain0r** [comment]
Hi there,

there's nothing to worry about, it looks worse than it is.

This error basically says that ampd didn't find any covers in that directory.

Anyway, your ticket made change the method so that it looks less dramatic. It's in the  [ampd-1.1.4](https://github.com/rain0r/ampd/releases/tag/ampd-1.1.4)  release.

Thanks for using ampd!

**Comment by nowrap** [comment]
Hello rain0r,
thx for the answer and the new release.

I switched to the 1.1.4 version. But i still got the error, even if there is a cover.jpg.
So my first quess was, escaping or quoting of paths with blanks maybe the problem.

But a second view to the code lines mentioned in the exception revealed my problem:
> Path path = Paths.get(musicDirectory, trackFilePath.get());
> List<Path> covers = AmpdUtils.scanDir(path);

>   @Value("${mpd.music.directory:}")
>   // ':' sets an empty str if the prop is not set
>   private String musicDirectory;

musicDirectory is empty if not set.
Now it works ;)

Regards
nowrap
